spring.application.name=espalhai-backend

# H2 Database Configuration
spring.datasource.url=jdbc:h2:mem:espalhaidb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Security
espalhai.jwt.secret=9a67475b459d990518274a3246a97340087a35724af556a77340324546a77340
espalhai.jwt.expiration=86400000

# File Upload
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB


# Server
server.port=8080
